export const DECREMENT_GLOBAL_LOADING_QUEUE = "DECREMENT_GLOBAL_LOADING_QUEUE";
export const INCREMENT_GLOBAL_LOADING_QUEUE = "INCREMENT_GLOBAL_LOADING_QUEUE";
export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";
export const TOGGLE_TEXT_SIZE = "TOGGLE_TEXT_SIZE";
